# Generated by Django 3.2.8 on 2022-03-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210302_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='facebook',
            field=models.URLField(default='https://www.facebook.com/', verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin',
            field=models.URLField(default='https://www.linkedin.com/', verbose_name='Linkedin'),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter',
            field=models.URLField(default='https://www.twitter.com/', verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
