# Generated by Django 3.2.8 on 2022-03-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_auto_20220302_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('Могу научить', 'Могу научить'), ('Хочу научиться', 'Хочу научиться')], default='Могу научить', max_length=25),
        ),
    ]
